[versions]
agp = "8.2.0"
junit = "6.0.0"
kotlin = "2.2.21"
pluginPublish = "1.3.1"

[libraries]
agp-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
agp-gradle-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
java-gradle-plugin = { id = "org.gradle.java-gradle-plugin"}